# Generated by Django 5.0.8 on 2024-12-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villas/'),
        ),
    ]
